ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 1.41  # From https://hello-robot.com/product
    RADIUS: 0.17  # From https://hello-robot.com/product
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 480              # From https://arxiv.org/pdf/2109.10892.pdf
    HEIGHT: 640             # From https://arxiv.org/pdf/2109.10892.pdf
    HFOV: 42                # From https://www.intelrealsense.com/depth-camera-d435
    POSITION: [0, 1.31, 0]  # From https://arxiv.org/pdf/2109.10892.pdf
    ORIENTATION: [-0.5235, 0.0, 0.0]
  DEPTH_SENSOR:
    WIDTH: 480              # From https://arxiv.org/pdf/2109.10892.pdf
    HEIGHT: 640             # From https://arxiv.org/pdf/2109.10892.pdf
    HFOV: 42                # From https://www.intelrealsense.com/depth-camera-d435
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 1.31, 0]  # From https://arxiv.org/pdf/2109.10892.pdf
    ORIENTATION: [-0.5235, 0.0, 0.0]
  ACTION_SPACE_CONFIG: "v0"
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2 # 2 x Agent Radius
  SENSORS: ['NOISE_FREE_POSE_SENSOR', 'POINTGOAL_SENSOR']
  POINTGOAL_SENSOR:
    GOAL_FORMAT: POLAR
    DIMENSIONALITY: 2
  SUCCESS:
    SUCCESS_DISTANCE: 0.2 # 2 x Agent Radius
  GOAL_SENSOR_UUID: pointgoal
  MEASUREMENTS: ['DISTANCE_TO_GOAL', "SUCCESS", "SPL", "SOFT_SPL"]
DATASET:
  TYPE: PointNav-v1
  SPLIT: val
  DATA_PATH: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
