ENVIRONMENT:
  MAX_EPISODE_STEPS: 10000
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 1.41  # From https://hello-robot.com/product
    RADIUS: 0.17  # From https://hello-robot.com/product
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 480              # From https://arxiv.org/pdf/2109.10892.pdf
    HEIGHT: 640             # From https://arxiv.org/pdf/2109.10892.pdf
    HFOV: 42                # From https://www.intelrealsense.com/depth-camera-d435
    POSITION: [0, 1.31, 0]  # From https://arxiv.org/pdf/2109.10892.pdf
    ORIENTATION: [-0.5235, 0.0, 0.0]
  DEPTH_SENSOR:
    WIDTH: 480              # From https://arxiv.org/pdf/2109.10892.pdf
    HEIGHT: 640             # From https://arxiv.org/pdf/2109.10892.pdf
    HFOV: 42                # From https://www.intelrealsense.com/depth-camera-d435
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 1.31, 0]  # From https://arxiv.org/pdf/2109.10892.pdf
    ORIENTATION: [-0.5235, 0.0, 0.0]
TASK:
  TYPE: Exp-v0
  SENSORS: ['GT_POSE_SENSOR', 'GT_EGO_MAP', 'GT_EGO_WALL_MAP']
  GT_EGO_MAP:
    MAP_SIZE: 65
    MAP_SCALE: 0.05
    HEIGHT_THRESH: [0.2, 1.5]
  GT_EGO_WALL_MAP:
    MAP_SIZE: 65
    MAP_SCALE: 0.05
    HEIGHT_THRESH: [1.0, 1.5]
  MEASUREMENTS: []
DATASET:
  TYPE: Exploration-v1
  SPLIT: val
  DATA_PATH: data/datasets/exploration/gibson/v1_condensed/{split}/{split}.json.gz
